### ISSUE TITLE
Should we rename profile.dtd to Profile.dtd?

### ISSUE THREAD

**Issue by meleno10** [rsanchez-wsu/sp16-ceg3120#89] opened 2016-02-24 22:43 UTC
This would match the casing in our XML files (and most if not all others)

**Comment by meleno10** [comment] 2016-03-09 22:06
We have decided to rename it to Preferences.dtd

**Comment by rsanchez-wsu** [comment] 2016-03-16 16:33
@meleno10 Was there a code change associated with closing this ticket?  If so, please add a comment referencing the applicable commit(s).  If there was no code change, lease describe in a bit more detail why the issue is now considered closed.

**Closed as completed** 2016-03-16 20:46 UTC
Labels: question, priority-low, team-1
